---
title: '`Week 4` Reproducible Research'
author: '`r if(knitr::is_html_output()) {"&#x1f468;&#x1F3FB;&#x200d;&#x1f4bb; Anderson H Uyekita"} else {NULL}`'
output:
  github_document: default
params:
  author: "Anderson H Uyekita"
  course: "Reproducible Research"
  course_url: "https://www.coursera.org/learn/reproducible-research"
  specialization: "Data Science: Foundations using R Specialization"
  specialization_url: "https://www.coursera.org/specializations/data-science-foundations-r"
  instructor: "Roger D Peng"
  course_start: !r lubridate::ymd("2022/06/29")
  course_finish: !r lubridate::ymd("2022/06/29")
  week: "Week 4"
  slug: 'Week%204'
---

```{r setup, include=FALSE,message=FALSE,warning=FALSE,cache=TRUE}
# Defining document chunks options
knitr::opts_chunk$set(echo = TRUE,cache=TRUE,message=FALSE,warning=FALSE)

# Loading required libraries
library(rmarkdown)
library(lubridate)
library(ggplot2)
```

* `r if(!knitr::is_html_output()) {sprintf(fmt = "&#x1f468;&#x1F3FB;&#x200d;&#x1f4bb; Author: %s", params$author)}`
* `r sprintf(fmt = "&#x1f4da; Specialization: [%s](%s){target='_blank' rel='noopener'}", params$specialization, params$specialization_url)`
* `r sprintf(fmt = "&#x1f4d6; Course: [%s](%s){target='_blank' rel='noopener'}", params$course, params$course_url)`
    * `r sprintf(fmt = "&#x1F9D1;&#x200d;&#x1F3EB; Instructor: %s", params$instructor)`
* `r sprintf(fmt = "&#x1F4C6; %s", params$week)`
    * `r sprintf(fmt = "&#x1F6A6; Start: %s", format(params$course_start, "%A, %d %B %Y"))`
    * `r sprintf(fmt = "&#x1F3C1; Finish: %s", format(params$course_finish, "%A, %d %B %Y"))`

--------------------------------------------------------------------------------

#### Assignments & Deliverables

* This week there is no &#x1F4DD; Quiz
* [&#x1F680; Course Project 2 Repository](https://github.com/AndersonUyekita/reproducible-research_course-project-2)

--------------------------------------------------------------------------------

#### Slides

* Lesson 1: Caching Computations [](){id="lesson-1"}
    * [Caching Computations][l1]
* Lesson 2: Case Study: Air Pollution [](){id="lesson-2"}
    * [Identifying Harmful Constituents in Particulate Matter Air Pollution][l2]
* Lesson 3: Case Study: High Throughput Biology [](){id="lesson-3"}
    * [Case Study: High Throughput Biology][l3]
    
[l1]: ./slides/4_1_caching.pdf
[l2]: ./slides/4_2_case-study-ap.pdf
[l3]: ./slides/4_3_case-study-baggerly.pdf

--------------------------------------------------------------------------------

#### Description

> This week there are two case studies involving the importance of reproducibility in science for you to watch.

--------------------------------------------------------------------------------

## Class Notes

### [<kbd>Lesson 1</kbd>](#lesson-1) Caching Computations

The `cacher` package is no longer available on CRAN.

* https://cran.r-project.org/web/packages/cacher/index.html

```
Package ‘cacher’ was removed from the CRAN repository.

Formerly available versions can be obtained from the archive.

Archived on 2014-09-19 as vignette locations were never updated for R 3.1.0.

Please use the canonical form https://CRAN.R-project.org/package=cacher to link to this page.
```

**Readings**

* https://www.r-bloggers.com/2020/04/caching-in-r/

### [<kbd>Lesson 1</kbd>](#lesson-2) Case Study: Air Pollution

**Lessons Learned**

* Reproducibility of NMMAPS allowed for a secondary analysis (and linking with PM chemical constituent data) investigating a novel hypothesis (Lippmann et al.)
* Reproducibility also allowed for a critique of that new analysis and some additional new analysis (Dominici et al.)
* Original hypothesis not necessarily invalidated, but evidence not as strong as originally suggested (more work should be done)
* Reproducibility allows for the scientific discussion to occur in a timely and informed manner
* This is how science works

### [<kbd>Lesson 1</kbd>](#lesson-3) Case Study: High Throughput Biology

Lecture about how to create reproducible research.