---
title: '`Week 3` Reproducible Research'
author: '`r if(knitr::is_html_output()) {"&#x1f468;&#x1F3FB;&#x200d;&#x1f4bb; Anderson H Uyekita"} else {NULL}`'
output:
  github_document: default
params:
  author: "Anderson H Uyekita"
  course: "Reproducible Research"
  course_url: "https://www.coursera.org/learn/reproducible-research"
  specialization: "Data Science: Foundations using R Specialization"
  specialization_url: "https://www.coursera.org/specializations/data-science-foundations-r"
  instructor: "Roger D Peng"
  course_start: !r lubridate::ymd("2022/06/28")
  course_finish: !r lubridate::ymd("2022/06/29")
  week: "Week 3"
  slug: 'Week%203'
---

```{r setup, include=FALSE,message=FALSE,warning=FALSE,cache=TRUE}
# Defining document chunks options
knitr::opts_chunk$set(echo = TRUE,cache=TRUE,message=FALSE,warning=FALSE)

# Loading required libraries
library(rmarkdown)
```

* `r if(!knitr::is_html_output()) {sprintf(fmt = "&#x1f468;&#x1F3FB;&#x200d;&#x1f4bb; Author: %s", params$author)}`
* `r sprintf(fmt = "&#x1f4da; Specialization: [%s](%s){target='_blank' rel='noopener'}", params$specialization, params$specialization_url)`
* `r sprintf(fmt = "&#x1f4d6; Course: [%s](%s){target='_blank' rel='noopener'}", params$course, params$course_url)`
    * `r sprintf(fmt = "&#x1F9D1;&#x200d;&#x1F3EB; Instructor: %s", params$instructor)`
* `r sprintf(fmt = "&#x1F4C6; %s", params$week)`
    * `r sprintf(fmt = "&#x1F6A6; Start: %s", format(params$course_start, "%A, %d %B %Y"))`
    * `r sprintf(fmt = "&#x1F3C1; Finish: %s", format(params$course_finish, "%A, %d %B %Y"))`

--------------------------------------------------------------------------------

#### Assignments & Deliverables

* This week there is no &#x1F4DD; Quiz

--------------------------------------------------------------------------------

#### Slides

* Lesson 1: Communicating Results [](){id="lesson-1"}
    * [Specifying Levels of Details][l1]
* Lesson 2: RPubs [](){id="lesson-2"}
* Lesson 3: Reproducible Research Checklist [](){id="lesson-3"}
    * [What to Do and What Not to Do][l3]
* Lesson 4: Evidence-based Data Analysis [](){id="lesson-4"}
    * [Evidence based data analysis][l4]

[l1]: ./slides/3_1_levels-of-detail.pdf
[l3]: ./slides/3_3_checklist.pdf
[l4]: ./slides/3_4_evidence-based-data-analysis.pdf

--------------------------------------------------------------------------------

#### Description

> This week covers what one could call a basic check list for ensuring that a data analysis is reproducible. While it's not absolutely sufficient to follow the check list, it provides a necessary minimum standard that would be applicable to almost any area of analysis.

--------------------------------------------------------------------------------

## Class Notes

### [<kbd>Lesson 1</kbd>](#lesson-1) Communicating Results

**tl;tr**

* People are busy, especially managers and leaders
* Results of data analyses are sometimes presented in oral form, but often the first cut is presented via email
* It is often useful to breakdown the results of an analysis into different levels of granularity / detail

### [<kbd>Lesson 2</kbd>](#lesson-2) RPubs

* https://rpubs.com

### [<kbd>Lesson 3</kbd>](#lesson-3) Reproducible Research Checklist

**Summary**

* Are we doing good science?
* Was any part of this analysis done by hand?
    * If so, are those parts precisely document?
    * Does the documentation match reality?
* Have we taught a computer to do as much as possible (i.e. coded)?
    * `download.file()`
* Are we using a version control system?
    * `Github`
* Have we documented our software environment?
    * `sessinInfo()`
    * `set.seed()`
* Have we saved any output that we cannot reconstruct from original data + code?
* How far back in the analysis pipeline can we go before our results are no longer (automatically) reproducible?

### [<kbd>Lesson 4</kbd>](#lesson-4) Evidence-based Data Analysis

**Replication**

* Focuses on **the validity of the scientific claim**
* "Is this claim true?"
* The ultimate standard for strengthening scientific evidence
* **New investigators, data, analytical methods, laboratories, instruments, etc.**
* Particularly important in studies that can impact broad policy or regulatory decisions

**Reproducibility**

* Focuses on **the validity of the data analysis**
* "Can we trust this analysis?"
* Arguably a minimum standard for any scientific study
* New investigators, same data, same methods
* Important when replication is impossible

**Summary**

* Reproducible research is important, but does not necessarily solve the critical question of whether a data analysis is trustworthy
* Reproducible research focuses on the most "downstream" aspect of research dissemination
* Evidence-based data analysis would provide standardized, best practices for given scientific areas and questions
* Gives reviewers an important tool without dramatically increasing the burden on them
* More effort should be put into improving the quality of "upstream" aspects of scientific research
