---
title: '`Week 1` Reproducible Research'
author: '`r if(knitr::is_html_output()) {"&#x1f468;&#x1F3FB;&#x200d;&#x1f4bb; Anderson H Uyekita"} else {NULL}`'
output:
  github_document: default
params:
  author: "Anderson H Uyekita"
  course: "Reproducible Research"
  course_url: "https://www.coursera.org/learn/reproducible-research"
  specialization: "Data Science: Foundations using R Specialization"
  specialization_url: "https://www.coursera.org/specializations/data-science-foundations-r"
  instructor: "Roger D Peng"
  course_start: !r lubridate::ymd("2022/06/20")
  course_finish: !r lubridate::ymd("2022/06/22")
  week: "Week 1"
  slug: 'Week%201'
---

```{r setup, include=FALSE,message=FALSE,warning=FALSE,cache=TRUE}
# Defining document chunks options
knitr::opts_chunk$set(echo = TRUE,cache=TRUE,message=FALSE,warning=FALSE)

# Loading required libraries
library(rmarkdown)
library(lubridate)
```

`r if(!knitr::is_html_output()) {sprintf(fmt = "* &#x1f468;&#x1F3FB;&#x200d;&#x1f4bb; Author: %s", params$author)}`
`r sprintf(fmt = "* &#x1f4da; Specialization: [%s](%s){target='_blank' rel='noopener'}", params$specialization, params$specialization_url)`
`r sprintf(fmt = "* &#x1f4d6; Course: [%s](%s){target='_blank' rel='noopener'}", params$course, params$course_url)`
    `r sprintf(fmt = "* &#x1F9D1;&#x200d;&#x1F3EB; Instructor: %s", params$instructor)`
`r sprintf(fmt = "* &#x1F4C6; %s", params$week)`
    `r sprintf(fmt = "* &#x1F6A6; Start: %s", format(params$course_start, "%A, %d %B %Y"))`
    `r sprintf(fmt = "* &#x1F3C1; Finish: %s", format(params$course_finish, "%A, %d %B %Y"))`

--------------------------------------------------------------------------------

#### Assignments & Deliverables

* [&#x1F4DD; Quiz 1](./quiz-1_reproducible-research.md)

--------------------------------------------------------------------------------

#### Slides

* Lesson 1: Concepts and Ideas [](){id="lesson-1"}
    * [Concepts and Ideas][l1_1]
* Lesson 2: Structure of a Data Analysis [](){id="lesson-2"}
    * [Structure of a Data Analysis - Part 1][l2_1]
    * [Structure of a Data Analysis - Part 2][l2_2]
* Lesson 3: Organizing Your Analysis [](){id="lesson-3"}
    * [Organizing Your Analysis][l3_1]

[l1_1]: ./slides/1_1_repro-research.pdf
[l2_1]: ./slides/1_2_1_structure-of-a-data-analysis-1.pdf
[l2_2]: ./slides/1_2_2_structure-of-a-data-analysis-2.pdf
[l3_1]: ./slides/1_3_organizing-a-data-analysis.pdf

--------------------------------------------------------------------------------

#### Description

> This week will cover the basic ideas of reproducible research since they may be unfamiliar to some of you. We also cover structuring and organizing a data analysis to help make it more reproducible. I recommend that you watch the videos in the order that they are listed on the web page, but watching the videos out of order isn't going to ruin the story.

--------------------------------------------------------------------------------

## Class Notes

### [<kbd>Lesson 1</kbd>](#lesson-1) Concepts and Ideas

Replication: Based on an experiment, I will try to do it using my data following a third party's instructions (computer code).

Reproduction: I will use the same dataset and computer code to get the same results.

**Summary**

* Reproducible research is important as a minimum standard, particularly for studies that are difficult to replicate  
* Infrastructure is needed for creating and distributing reproducible documents, beyond  what is currently available  
* There is a growing number of tools for creating reproducible documents  


### [<kbd>Lesson 2</kbd>](#lesson-2) Structure of a Data Analysis

Steps in a data analysis Steps in a data analysis

* Define the question
* Define the ideal data set
* Determine what data you can access
* Obtain the data
* Clean the data
* Exploratory data analysis
* Statistical prediction/modeling
* Interpret results
* Challenge results
* Synthesize/write up results
* Create reproducible code


### [<kbd>Lesson 3</kbd>](#lesson-3) Organizing Your Analysis

Data analysis files

**Summary**

* Data
    * Raw data
    * Processed data (it should be tidy)
* Figures
    * Exploratory figures
    * Final figures
* R code
    * Raw / unused scripts
    * Final scripts
    * R Markdown files
* Text
    * README files
    * Text of analysis / report