---
title: '`Week 2` Reproducible Research'
author: '`r if(knitr::is_html_output()) {"&#x1f468;&#x1F3FB;&#x200d;&#x1f4bb; Anderson H Uyekita"} else {NULL}`'
output:
  github_document: default
params:
  author: "Anderson H Uyekita"
  course: "Reproducible Research"
  course_url: "https://www.coursera.org/learn/reproducible-research"
  specialization: "Data Science: Foundations using R Specialization"
  specialization_url: "https://www.coursera.org/specializations/data-science-foundations-r"
  instructor: "Roger D Peng"
  course_start: !r lubridate::ymd("2022/06/23")
  course_finish: !r lubridate::today()
  week: "Week 2"
  slug: 'Week%202'
---

```{r setup, include=FALSE,message=FALSE,warning=FALSE,cache=TRUE}
# Defining document chunks options
knitr::opts_chunk$set(echo = TRUE,cache=TRUE,message=FALSE,warning=FALSE)

# Loading required libraries
library(rmarkdown)
library(lubridate)
```

`r if(!knitr::is_html_output()) {sprintf(fmt = "* &#x1f468;&#x1F3FB;&#x200d;&#x1f4bb; Author: %s", params$author)}`
`r sprintf(fmt = "* &#x1f4da; Specialization: [%s](%s){target='_blank' rel='noopener'}", params$specialization, params$specialization_url)`
`r sprintf(fmt = "* &#x1f4d6; Course: [%s](%s){target='_blank' rel='noopener'}", params$course, params$course_url)`
    `r sprintf(fmt = "* &#x1F9D1;&#x200d;&#x1F3EB; Instructor: %s", params$instructor)`
`r sprintf(fmt = "* &#x1F4C6; %s", params$week)`
    `r sprintf(fmt = "* &#x1F6A6; Start: %s", format(params$course_start, "%A, %d %B %Y"))`
    `r sprintf(fmt = "* &#x1F3C1; Finish: %s", format(params$course_finish, "%A, %d %B %Y"))`

--------------------------------------------------------------------------------

#### Assignments & Deliverables

* [&#x1F4DD; Quiz 2](./quiz-2_reproducible-research.md)
* [&#x1F680; Course Project 1 Repository](https://github.com/AndersonUyekita/reproducible-research_course-project-1)

--------------------------------------------------------------------------------

#### Slides

* Lesson 1: Markdown & R Markdown [](){id="lesson-1"}
    * [Markdown][l1_1]
    * [R Markdown][l1_2]
* Lesson 2: knitr [](){id="lesson-2"}
    * [knitr][l2_1]

[l1_1]: ./slides/2_1_1_markdown.pdf
[l1_2]: ./slides/2_1_2_r-markdown.pdf
[l2_1]: ./slides/2_2_knitr.pdf

--------------------------------------------------------------------------------

#### Description

> This week we cover some of the core tools for developing reproducible documents. We cover the literate programming tool knitr and show how to integrate it with Markdown to publish reproducible web documents. We also introduce the first peer assessment which will require you to write up a reproducible data analysis using knitr.

--------------------------------------------------------------------------------

## Class Notes

### [<kbd>Lesson 1</kbd>](#lesson-1) Markdown & R Markdown

**Markdown**

What is Markdown?

> * Created by John Gruber and Aaron Swartz
> * A simplified version of "markup" languages
> * Allows one to focus on writing as opposed to formatting
> * Simple/minimal intuitive formatting elements
> * Easily converted to valid HTML (and other formats) using existing tools
> * Complete information is available at http://daringfireball.net/projects/markdown/
> * Some background information at http://daringfireball.net/2004/03/dive_into_markdown

**R Markdown**

What is R Markdown?

> * R markdown is the integration of R code with markdown
> * Allows one to create documents containing "live" R code
> * R code is evaluated as part of the processing of the markdown
> * Results from R code are inserted into markdown document
> * A core tool in literate statistical programming
> * R markdown can be converted to standard markdown using the knitr package in R
> * Markdown can be converted to HTML using the markdown package in R
> * Any basic text editor can be used to create a markdown document; no special editing tools needed
> * The R markdown --> markdown --> HTML work flow can be easily managed using R Studio (but not required)
> * These slides were written in R markdown and converted to slides using the slidify package

### [<kbd>Lesson 2</kbd>](#lesson-2) knitr

**Summary**

> * Literate statistical programming can be a useful way to put text, code, data, output all in one document
> * knitr is a powerful tool for integrating code and text in a simple document format
